name: kuzzle
version: 2.4.4
description: A library to interact with kuzzle API. A backend software,
  self-hostable and ready to use to power modern cross-platform apps.
homepage: https://github.com/kuzzleio/sdk-dart
environment:
  sdk: ">=2.10.0 <3.0.0"
dependencies:
  pedantic: ^1.9.0
  meta: ^1.1.8
  uuid: ^2.0.4
  http: ^0.12.2
dev_dependencies:
  test: ^1.14.2
  coverage: ^0.13.9
