name: Deployment Doc Prod

on:
  push:
    branches:
      - master
      - 1-stable

jobs:
  dead-links:
    name: Dead links
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - uses: actions/setup-node@v1.4.4
        with:
          node-version: "12"
      - uses: ./.github/actions/dead-links

  doc-snippets:
    name: Doc Snippets
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - uses: actions/setup-node@v1.4.4
        with:
          node-version: "12"
      - uses: ./.github/actions/doc-snippets

  tests:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - uses: cedx/setup-dart@v2
      - uses: ./.github/actions/tests

  doc-prod:
    name: Deployment Doc Prod
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: [dead-links, doc-snippets]
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - uses: ./.github/actions/deploy-doc
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        with:
          FRAMEWORK_BRANCH: master
          S3_BUCKET: docs.kuzzle.io
          CLOUDFRONT_ID: E3D6RP0POLCJMM
          REGION: us-west-2
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}

  deploy-package:
    name: Publish Package
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: [tests]
    steps:
      - uses: actions/checkout@v2
      - uses: cedx/setup-dart@v2
        with:
            accessToken: ${{ secrets.PUB_ACCESS_TOKEN }}
            refreshToken: ${{ secrets.PUB_REFRESH_TOKEN }}
      - run: pub publish --force
      
